### ISSUE TITLE
Relative path issue in react popup?

### ISSUE THREAD

**Issue by djMax** [thmsgbrt/Chrome-Extension-with-React-and-Typescript-Starter-Pack#14]
I'm getting a blank screen on the popup, and I think it's because the paths in the compiled index.html are like this:

```
  <link href="/static/css/main.5f361e03.chunk.css" rel="stylesheet">
  <script src="/static/js/runtime-main.e6ce7b14.js"></script>
```

But that's not right, because they are in `/popup/static/...`

**Comment by thmsgbrt** [comment]
Hi @djMax ,

Indeed, you need to add the following to the package.json of the popup
`"homepage": "."`

It must have been removed when I updated CRA somehow...
I'm sorry and thanks for reporting the issue.
