### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ctownshend** [thmsgbrt/Chrome-Extension-with-React-and-Typescript-Starter-Pack#3]
I would like to make some requests. Today I added Options page. Would be good to have that in the article or read me. Happy to write it up.

Also I have been evaluating other frameworks. and found webextension-toolbox had a) alot of likes and b) had the ability to generate a cross-browser extension with support for vendor keys in manifest.json etc. Problem was it does not support typescript ATM. Wondering either a) how hard would it be to merge what you have done with what they have done or b) add vendor support to your extension. especially vendor specific manifest.json keys. like 
`__firefox__browser_specific": {
    "gecko": {
      "id": "ctownshend@sonatype.com",
      "strict_min_version": "42.0"
    }
  }
`

**Comment by thmsgbrt** [comment]
Hi, @ctownshend,
This repo is the finished project of the article that I wrote. For this reason, I can't apply changes to it without updating the article.

Also, the article has for objective to explain how to create a basic extension for Chrome and I don't want to complexify it too much.

About webextension-toolbox, my project may be completely different from theirs. I think you should open a feature request there, I would also love if they could support TS! 
As it is pretty much only a problem of webpack config, my guess would be that they can implement it quite easily...  Hopefully!

**Comment by ctownshend** [comment]
Hi Thanks Thomas, I understand, I enjoyed your article. And yes I worked with the webextension-toolbox and have added TS myself. I will work with them and send a PR. All the best.
