### ISSUE TITLE
All background reds

### ISSUE THREAD

**Issue by whalemare** [thmsgbrt/Chrome-Extension-with-React-and-Typescript-Starter-Pack#6]
When I run your extensions, all background on all websites makes red.
<img width="733" alt="Снимок экрана 2020-06-03 в 14 05 23" src="https://user-images.githubusercontent.com/9128731/83618053-20ba5480-a5b4-11ea-8a60-8b61ff244add.png">

**Comment by thmsgbrt** [comment]
Hi @whalemare, Check the css files ;) 
It added it to show that it works.
